[package]
name = "secreto"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[dependencies]
gpgme = "0.11.0"
relm4 = { version = "0.9.0", features = ["libadwaita", "gnome_46"] }
relm4-macros = "0.9.0"
